version: '3.8'

services:
  whisper:
    build:
      context: ./whisper
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # env_file: .env
    # depends_on:
    #   - mongo-server
    volumes:
      - ./whisper:/python-docker
  api:
    build: ./src
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/app:/usr/src/app/
    ports:
      - 8002:8000
    # restart: "no"
  # mongo-server:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"