version: '3'

services:
  whisper:
    build:
      context: ./whisper
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # env_file: .env
    # depends_on:
    #   - mongo-server
    volumes:
      - ./whisper:/python-docker
  # mongo-server:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"